### ISSUE TITLE
Navigate downwards selection shortcut should by default focus on the first topic

### ISSUE THREAD

**Issue by wktang** [NodeBB-Community/nodebb-plugin-shortcuts#17]
When I click `J` to navigate downwards, it should by default focus on the first topic.

Currently if there are other item cluster that appear before the topics, it defaults to that cluster (such as Sort by / Topic Tools) which is usually not what user expects.

**Comment by frissdiegurke** [comment]
I've improved your solution by changing the defined object to an array.
Now the order of areas is defined by the following priority:
 1. The selector that is used for the area (by the order within `theme.selection` array).
 2. The occurrence of the first item (parent iff `selector.isParent`)

**Comment by wktang** [comment]
Thanks! The improvement is indeed much better :D
