### ISSUE TITLE
Discard post shortcut should always prompt user confirmation dialog

### ISSUE THREAD

**Issue by wktang** [NodeBB-Community/nodebb-plugin-shortcuts#18]
Currently if I press the discard post shortcut while composing a reply, the post is discarded immediately without prompting the confirmation dialog: "Are you sure you want to discard this post?" This may cause user frustration as the post is lost forever by accidentally pressing the shortcut.

If I typed something in the compose box, then blur the focus of the compose box by clicking outside of it, then press the shortcut it does prompt the confirmation dialog. It should prompt the dialog regardless whether the focus is in the compose box or not.

**Comment by frissdiegurke** [comment]
It actually just simulates a click on the discard button. Whether the dialog pops up is on the composers scope. It does not ask up to a few characters thought. This plugin should behave exactly like clicking "Discard" by hand.
Please check again whether clicking the discard button with similar composer content and changes does show the dialog. I'm not exactly sure about the conditions for that dialog to show up, it has something to do with key types and changes or content length thought.

**Comment by wktang** [comment]
Yes, clicking the discard button does show the dialog box.
